site_name: Data Engineering
site_description: Data Engineering class at ISAE-Supaero as part of the SDD program
site_url: https://supaerodatascience.github.io/DE/
site_dir: site
strict: false
use_directory_urls: false

theme:
  name: 'material'
  palette:
    primary: light blue
    accent: light blue
  logo: 'https://raw.githubusercontent.com/SupaeroDataScience/DE/master/src/favicon.ico'
  favicon: 'https://raw.githubusercontent.com/SupaeroDataScience/DE/master/src/favicon.ico'
  features:
    - toc.autohide
    - navigation.sections

repo_name: SupaeroDataScience/DE
repo_url: https://github.com/SupaeroDataScience/DE

nav:
- Overview:
  - Syllabus: index.md
- DE Fundamentals:
  - CTF: ctf.md
- Data Storage:
  - SQL: 0_1_databases.md
  - PostgreSQL: 0_2_postgres.md
  - Parallel DBMS: 0_3_dbms.md
- Data Computation:
  - Introduction: 1_1_overview.md
  - Cloud Computing:
    - Lectures: 1_2_cloud.md
    - TP: 1_2_gcp_handson.md
  - Containers, Docker:
    - Lecture: 1_3_containers.md
    - TP: 1_3_docker_tp.md
  - Google Cloud and Docker BE: 1_4_be.md
  - Recap Cloud & Docker: 1_5_conclusion.md
  - Distributed DBMS: 1_6_distributed.md
  - Reading List: 1_7_readings.md
- Data Distribution:
  - Introduction: 2_1_overview.md
  - Deployment:
    - Lectures: 2_2_deployment.md
    - TP: 2_2_deployment_tp.md
    - TP (Version Longue): 2_2_deployment_tp_long.md
  - Kubernetes:
    - TP: 2_3_kub_intro.md
  - Functional Programming: 2_4_functional.md
  - Hadoop and MapReduce: 2_5_mapreduce.md
  - Spark: 2_6_spark.md
  - Cloud DBMS: 2_7_cloud.md
  - Dask on Kubernetes: 2_8_dask.md
  - Dask project: 2_9_project.md

markdown_extensions:
- markdown.extensions.codehilite:
    guess_lang: false
- toc:
    permalink: 🔗
- admonition
- codehilite
- extra
- attr_list
- pymdownx.details
- pymdownx.superfences

plugins:
- search
