site_name: Data Engineering
site_description: Data Engineering class at ISAE-Supaero as part of the SDD program
site_url: https://supaerodatascience.github.io/DE/
site_dir: site
strict: false
use_directory_urls: false

theme:
  name: 'material'
  palette:
    primary: light blue
    accent: light blue
  logo: 'https://raw.githubusercontent.com/SupaeroDataScience/DE/master/src/favicon.ico'
  favicon: 'https://raw.githubusercontent.com/SupaeroDataScience/DE/master/src/favicon.ico'
  features:
    - toc.autohide
    - navigation.sections

repo_name: SupaeroDataScience/DE
repo_url: https://github.com/SupaeroDataScience/DE

nav:
- Overview: index.md
- Data Storage:
  - SQL: 0_1_databases.md
  - PostgreSQL: 0_3_postgres.md
  - ETL: 0_2_ETL.md
  - Project: 0_4_project.md
- Cloud Systems:
  - Introduction: 1_1_overview.md
  - Cloud Computing & Google Cloud Platform: 1_2_cloud.md
  - Containers, Docker: 1_3a_containers.md
  - Workshop GCP & Docker:
    - 1. Lecture: 1_4_be.md
    - 1. GCP Compute Workflow: 1_4a_gcp_workflow.md
    - 2. Docker Workflow: 1_4b_docker_workflow.md
    - 3. GCP Deployment Workflow: 1_4c_deployment_workflow.md
  - Workshop Deploy your ML model into production:
    - 1. Lecture: 1_5a_deployment.md
    - 2. Deploy your ML model into production: 1_5b_deployment_be.md
  - Recap & Reading List: 1_6_conclusion.md
- Cloud Data Engineering:
  - Introduction:
    - Overview: 2_1_overview.md
    - Hadoop and MapReduce: 2_5_mapreduce.md
  - Orchestration & Kubernetes:
    - Lectures: 2_2_orchestration.md
    - TP: 2_3_kub_handson.md
  - Spark: 2_6_spark.md
  - Dask on Kubernetes: 2_8_dask.md
  - Dask project: 2_9_project.md

markdown_extensions:
- markdown.extensions.codehilite:
    guess_lang: false
- toc:
    permalink: 🔗
- admonition
- codehilite
- extra
- attr_list
- def_list
- pymdownx.details
- pymdownx.superfences

plugins:
- search
